// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppConfig {
  final int oscPort;
  final String? deviceName;
  final int bufferSize;
  final List<RoomConfig> rooms;

  const AppConfig({
    required this.oscPort,
    this.deviceName,
    required this.bufferSize,
    required this.rooms,
  });

  @override
  int get hashCode =>
      oscPort.hashCode ^
      deviceName.hashCode ^
      bufferSize.hashCode ^
      rooms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfig &&
          runtimeType == other.runtimeType &&
          oscPort == other.oscPort &&
          deviceName == other.deviceName &&
          bufferSize == other.bufferSize &&
          rooms == other.rooms;
}

class RoomConfig {
  final String id;
  final String name;
  final String colorHex;
  final double volume;
  final String clearOscAddress;
  final List<TrackConfig> tracks;

  const RoomConfig({
    required this.id,
    required this.name,
    required this.colorHex,
    required this.volume,
    required this.clearOscAddress,
    required this.tracks,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      colorHex.hashCode ^
      volume.hashCode ^
      clearOscAddress.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          colorHex == other.colorHex &&
          volume == other.volume &&
          clearOscAddress == other.clearOscAddress &&
          tracks == other.tracks;
}

class TrackConfig {
  final String id;
  final String name;
  final String filePath;
  final double volume;
  final bool isLoop;
  final int outputChannel;
  final String playOscAddress;
  final String stopOscAddress;

  const TrackConfig({
    required this.id,
    required this.name,
    required this.filePath,
    required this.volume,
    required this.isLoop,
    required this.outputChannel,
    required this.playOscAddress,
    required this.stopOscAddress,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      filePath.hashCode ^
      volume.hashCode ^
      isLoop.hashCode ^
      outputChannel.hashCode ^
      playOscAddress.hashCode ^
      stopOscAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          filePath == other.filePath &&
          volume == other.volume &&
          isLoop == other.isLoop &&
          outputChannel == other.outputChannel &&
          playOscAddress == other.playOscAddress &&
          stopOscAddress == other.stopOscAddress;
}
