// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppConfig {
  final Map<String, String> audioDevice;
  final OscConfig osc;
  final List<RoomConfig> rooms;

  const AppConfig({
    required this.audioDevice,
    required this.osc,
    required this.rooms,
  });

  @override
  int get hashCode => audioDevice.hashCode ^ osc.hashCode ^ rooms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfig &&
          runtimeType == other.runtimeType &&
          audioDevice == other.audioDevice &&
          osc == other.osc &&
          rooms == other.rooms;
}

class OscConfig {
  final String host;
  final int port;

  const OscConfig({required this.host, required this.port});

  @override
  int get hashCode => host.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OscConfig &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port;
}

class RoomConfig {
  final BigInt id;
  final String name;
  final double masterVolume;
  final String oscClear;
  final List<TrackConfig> tracks;

  const RoomConfig({
    required this.id,
    required this.name,
    required this.masterVolume,
    required this.oscClear,
    required this.tracks,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      masterVolume.hashCode ^
      oscClear.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          masterVolume == other.masterVolume &&
          oscClear == other.oscClear &&
          tracks == other.tracks;
}

class TrackConfig {
  final String file;
  final BigInt outputCh;
  final double volume;
  final bool isBgm;
  final bool loopPlay;
  final String oscPlay;
  final String oscStop;

  const TrackConfig({
    required this.file,
    required this.outputCh,
    required this.volume,
    required this.isBgm,
    required this.loopPlay,
    required this.oscPlay,
    required this.oscStop,
  });

  @override
  int get hashCode =>
      file.hashCode ^
      outputCh.hashCode ^
      volume.hashCode ^
      isBgm.hashCode ^
      loopPlay.hashCode ^
      oscPlay.hashCode ^
      oscStop.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackConfig &&
          runtimeType == other.runtimeType &&
          file == other.file &&
          outputCh == other.outputCh &&
          volume == other.volume &&
          isBgm == other.isBgm &&
          loopPlay == other.loopPlay &&
          oscPlay == other.oscPlay &&
          oscStop == other.oscStop;
}
