// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/error.dart';
import 'api/simple.dart';
import 'common/config.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1880573449;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_atmos_mixer_pro',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleApiClearRoom({required String roomId});

  Stream<EngineStateUpdate> crateApiSimpleApiCreateEngineStateStream();

  Stream<String> crateApiSimpleApiCreateLogStream();

  Stream<Float32List> crateApiSimpleApiCreateVuStream();

  Future<AppConfig> crateApiSimpleApiGetConfig({required String path});

  Future<int> crateApiSimpleApiGetDeviceChannelCount({
    required String deviceName,
  });

  Future<List<OutputDeviceInfo>> crateApiSimpleApiGetOutputDevices();

  Future<void> crateApiSimpleApiInitApp();

  Future<void> crateApiSimpleApiPlayTrack({
    required String roomId,
    required String trackId,
  });

  Future<void> crateApiSimpleApiPreloadAllSounds({required AppConfig config});

  Future<void> crateApiSimpleApiSaveConfig({
    required String path,
    required AppConfig config,
  });

  Future<void> crateApiSimpleApiSetMasterVolume({
    required String roomId,
    required double volume,
  });

  Future<void> crateApiSimpleApiSetTrackVolume({
    required String roomId,
    required String trackId,
    required double volume,
  });

  Future<void> crateApiSimpleApiStartAudioEngine({String? deviceName});

  Future<void> crateApiSimpleApiStartOscListener({
    required int port,
    required AppConfig config,
  });

  Future<void> crateApiSimpleApiStopAll();

  Future<void> crateApiSimpleApiStopTrack({
    required String roomId,
    required String trackId,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleApiClearRoom({required String roomId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_atmos_error,
        ),
        constMeta: kCrateApiSimpleApiClearRoomConstMeta,
        argValues: [roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiClearRoomConstMeta =>
      const TaskConstMeta(debugName: "api_clear_room", argNames: ["roomId"]);

  @override
  Stream<EngineStateUpdate> crateApiSimpleApiCreateEngineStateStream() {
    final sink = RustStreamSink<EngineStateUpdate>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_engine_state_update_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleApiCreateEngineStateStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleApiCreateEngineStateStreamConstMeta =>
      const TaskConstMeta(
        debugName: "api_create_engine_state_stream",
        argNames: ["sink"],
      );

  @override
  Stream<String> crateApiSimpleApiCreateLogStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleApiCreateLogStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleApiCreateLogStreamConstMeta =>
      const TaskConstMeta(
        debugName: "api_create_log_stream",
        argNames: ["sink"],
      );

  @override
  Stream<Float32List> crateApiSimpleApiCreateVuStream() {
    final sink = RustStreamSink<Float32List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_list_prim_f_32_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleApiCreateVuStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleApiCreateVuStreamConstMeta =>
      const TaskConstMeta(
        debugName: "api_create_vu_stream",
        argNames: ["sink"],
      );

  @override
  Future<AppConfig> crateApiSimpleApiGetConfig({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleApiGetConfigConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiGetConfigConstMeta =>
      const TaskConstMeta(debugName: "api_get_config", argNames: ["path"]);

  @override
  Future<int> crateApiSimpleApiGetDeviceChannelCount({
    required String deviceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_atmos_error,
        ),
        constMeta: kCrateApiSimpleApiGetDeviceChannelCountConstMeta,
        argValues: [deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiGetDeviceChannelCountConstMeta =>
      const TaskConstMeta(
        debugName: "api_get_device_channel_count",
        argNames: ["deviceName"],
      );

  @override
  Future<List<OutputDeviceInfo>> crateApiSimpleApiGetOutputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_output_device_info,
          decodeErrorData: sse_decode_atmos_error,
        ),
        constMeta: kCrateApiSimpleApiGetOutputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiGetOutputDevicesConstMeta =>
      const TaskConstMeta(debugName: "api_get_output_devices", argNames: []);

  @override
  Future<void> crateApiSimpleApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "api_init_app", argNames: []);

  @override
  Future<void> crateApiSimpleApiPlayTrack({
    required String roomId,
    required String trackId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(trackId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_atmos_error,
        ),
        constMeta: kCrateApiSimpleApiPlayTrackConstMeta,
        argValues: [roomId, trackId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiPlayTrackConstMeta => const TaskConstMeta(
    debugName: "api_play_track",
    argNames: ["roomId", "trackId"],
  );

  @override
  Future<void> crateApiSimpleApiPreloadAllSounds({required AppConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_app_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_atmos_error,
        ),
        constMeta: kCrateApiSimpleApiPreloadAllSoundsConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiPreloadAllSoundsConstMeta =>
      const TaskConstMeta(
        debugName: "api_preload_all_sounds",
        argNames: ["config"],
      );

  @override
  Future<void> crateApiSimpleApiSaveConfig({
    required String path,
    required AppConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_app_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_atmos_error,
        ),
        constMeta: kCrateApiSimpleApiSaveConfigConstMeta,
        argValues: [path, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiSaveConfigConstMeta =>
      const TaskConstMeta(
        debugName: "api_save_config",
        argNames: ["path", "config"],
      );

  @override
  Future<void> crateApiSimpleApiSetMasterVolume({
    required String roomId,
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_f_32(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_atmos_error,
        ),
        constMeta: kCrateApiSimpleApiSetMasterVolumeConstMeta,
        argValues: [roomId, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiSetMasterVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "api_set_master_volume",
        argNames: ["roomId", "volume"],
      );

  @override
  Future<void> crateApiSimpleApiSetTrackVolume({
    required String roomId,
    required String trackId,
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(trackId, serializer);
          sse_encode_f_32(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_atmos_error,
        ),
        constMeta: kCrateApiSimpleApiSetTrackVolumeConstMeta,
        argValues: [roomId, trackId, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiSetTrackVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "api_set_track_volume",
        argNames: ["roomId", "trackId", "volume"],
      );

  @override
  Future<void> crateApiSimpleApiStartAudioEngine({String? deviceName}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(deviceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleApiStartAudioEngineConstMeta,
        argValues: [deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiStartAudioEngineConstMeta =>
      const TaskConstMeta(
        debugName: "api_start_audio_engine",
        argNames: ["deviceName"],
      );

  @override
  Future<void> crateApiSimpleApiStartOscListener({
    required int port,
    required AppConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          sse_encode_box_autoadd_app_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleApiStartOscListenerConstMeta,
        argValues: [port, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiStartOscListenerConstMeta =>
      const TaskConstMeta(
        debugName: "api_start_osc_listener",
        argNames: ["port", "config"],
      );

  @override
  Future<void> crateApiSimpleApiStopAll() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_atmos_error,
        ),
        constMeta: kCrateApiSimpleApiStopAllConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiStopAllConstMeta =>
      const TaskConstMeta(debugName: "api_stop_all", argNames: []);

  @override
  Future<void> crateApiSimpleApiStopTrack({
    required String roomId,
    required String trackId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(trackId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_atmos_error,
        ),
        constMeta: kCrateApiSimpleApiStopTrackConstMeta,
        argValues: [roomId, trackId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApiStopTrackConstMeta => const TaskConstMeta(
    debugName: "api_stop_track",
    argNames: ["roomId", "trackId"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<EngineStateUpdate>
  dco_decode_StreamSink_engine_state_update_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<Float32List> dco_decode_StreamSink_list_prim_f_32_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppConfig dco_decode_app_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppConfig(
      oscPort: dco_decode_u_16(arr[0]),
      deviceName: dco_decode_opt_String(arr[1]),
      bufferSize: dco_decode_u_32(arr[2]),
      rooms: dco_decode_list_room_config(arr[3]),
    );
  }

  @protected
  AtmosError dco_decode_atmos_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return AtmosError(message: dco_decode_String(arr[0]));
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AppConfig dco_decode_box_autoadd_app_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_config(raw);
  }

  @protected
  EngineStateUpdate dco_decode_engine_state_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EngineStateUpdate(
      activeRoomId: dco_decode_opt_String(arr[0]),
      duckingActive: dco_decode_bool(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<OutputDeviceInfo> dco_decode_list_output_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_output_device_info).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RoomConfig> dco_decode_list_room_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_room_config).toList();
  }

  @protected
  List<TrackConfig> dco_decode_list_track_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track_config).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  OutputDeviceInfo dco_decode_output_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return OutputDeviceInfo(
      name: dco_decode_String(arr[0]),
      maxChannels: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  RoomConfig dco_decode_room_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RoomConfig(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      colorHex: dco_decode_String(arr[2]),
      volume: dco_decode_f_32(arr[3]),
      clearOscAddress: dco_decode_String(arr[4]),
      tracks: dco_decode_list_track_config(arr[5]),
    );
  }

  @protected
  TrackConfig dco_decode_track_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return TrackConfig(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      filePath: dco_decode_String(arr[2]),
      volume: dco_decode_f_32(arr[3]),
      isLoop: dco_decode_bool(arr[4]),
      outputChannel: dco_decode_u_32(arr[5]),
      playOscAddress: dco_decode_String(arr[6]),
      stopOscAddress: dco_decode_String(arr[7]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<EngineStateUpdate>
  sse_decode_StreamSink_engine_state_update_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<Float32List> sse_decode_StreamSink_list_prim_f_32_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppConfig sse_decode_app_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_oscPort = sse_decode_u_16(deserializer);
    var var_deviceName = sse_decode_opt_String(deserializer);
    var var_bufferSize = sse_decode_u_32(deserializer);
    var var_rooms = sse_decode_list_room_config(deserializer);
    return AppConfig(
      oscPort: var_oscPort,
      deviceName: var_deviceName,
      bufferSize: var_bufferSize,
      rooms: var_rooms,
    );
  }

  @protected
  AtmosError sse_decode_atmos_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    return AtmosError(message: var_message);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AppConfig sse_decode_box_autoadd_app_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_config(deserializer));
  }

  @protected
  EngineStateUpdate sse_decode_engine_state_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_activeRoomId = sse_decode_opt_String(deserializer);
    var var_duckingActive = sse_decode_bool(deserializer);
    return EngineStateUpdate(
      activeRoomId: var_activeRoomId,
      duckingActive: var_duckingActive,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<OutputDeviceInfo> sse_decode_list_output_device_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OutputDeviceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_output_device_info(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RoomConfig> sse_decode_list_room_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RoomConfig>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_room_config(deserializer));
    }
    return ans_;
  }

  @protected
  List<TrackConfig> sse_decode_list_track_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrackConfig>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track_config(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OutputDeviceInfo sse_decode_output_device_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_maxChannels = sse_decode_u_32(deserializer);
    return OutputDeviceInfo(name: var_name, maxChannels: var_maxChannels);
  }

  @protected
  RoomConfig sse_decode_room_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_colorHex = sse_decode_String(deserializer);
    var var_volume = sse_decode_f_32(deserializer);
    var var_clearOscAddress = sse_decode_String(deserializer);
    var var_tracks = sse_decode_list_track_config(deserializer);
    return RoomConfig(
      id: var_id,
      name: var_name,
      colorHex: var_colorHex,
      volume: var_volume,
      clearOscAddress: var_clearOscAddress,
      tracks: var_tracks,
    );
  }

  @protected
  TrackConfig sse_decode_track_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_volume = sse_decode_f_32(deserializer);
    var var_isLoop = sse_decode_bool(deserializer);
    var var_outputChannel = sse_decode_u_32(deserializer);
    var var_playOscAddress = sse_decode_String(deserializer);
    var var_stopOscAddress = sse_decode_String(deserializer);
    return TrackConfig(
      id: var_id,
      name: var_name,
      filePath: var_filePath,
      volume: var_volume,
      isLoop: var_isLoop,
      outputChannel: var_outputChannel,
      playOscAddress: var_playOscAddress,
      stopOscAddress: var_stopOscAddress,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_engine_state_update_Sse(
    RustStreamSink<EngineStateUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_engine_state_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_prim_f_32_strict_Sse(
    RustStreamSink<Float32List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_config(AppConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.oscPort, serializer);
    sse_encode_opt_String(self.deviceName, serializer);
    sse_encode_u_32(self.bufferSize, serializer);
    sse_encode_list_room_config(self.rooms, serializer);
  }

  @protected
  void sse_encode_atmos_error(AtmosError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_app_config(
    AppConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_config(self, serializer);
  }

  @protected
  void sse_encode_engine_state_update(
    EngineStateUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.activeRoomId, serializer);
    sse_encode_bool(self.duckingActive, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_output_device_info(
    List<OutputDeviceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_output_device_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_room_config(
    List<RoomConfig> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_room_config(item, serializer);
    }
  }

  @protected
  void sse_encode_list_track_config(
    List<TrackConfig> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track_config(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_output_device_info(
    OutputDeviceInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.maxChannels, serializer);
  }

  @protected
  void sse_encode_room_config(RoomConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.colorHex, serializer);
    sse_encode_f_32(self.volume, serializer);
    sse_encode_String(self.clearOscAddress, serializer);
    sse_encode_list_track_config(self.tracks, serializer);
  }

  @protected
  void sse_encode_track_config(TrackConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_f_32(self.volume, serializer);
    sse_encode_bool(self.isLoop, serializer);
    sse_encode_u_32(self.outputChannel, serializer);
    sse_encode_String(self.playOscAddress, serializer);
    sse_encode_String(self.stopOscAddress, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
