// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../common/config.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AUDIO_ENGINE`, `OSC_SERVER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`

Future<void> startAudioEngine() =>
    RustLib.instance.api.crateApiSimpleStartAudioEngine();

Future<void> stopAudioEngine() =>
    RustLib.instance.api.crateApiSimpleStopAudioEngine();

Future<AppConfig> loadAppConfig({required String path}) =>
    RustLib.instance.api.crateApiSimpleLoadAppConfig(path: path);

Future<List<String>> getAvailableDevices() =>
    RustLib.instance.api.crateApiSimpleGetAvailableDevices();

Stream<String> startOscServer({required int port}) =>
    RustLib.instance.api.crateApiSimpleStartOscServer(port: port);

Future<void> stopOscServer() =>
    RustLib.instance.api.crateApiSimpleStopOscServer();
